import "./globals.css";
import { Outfit } from "next/font/google"
import { ClerkProvider } from '@clerk/nextjs';
import Provider from "./Provider"
import {Toaster} from "@/components/ui/sonner";

export const metadata = {
  title: "Gen LMS",
  description: "Generated by GEMINI",
};

const outfit = Outfit({
    subsets:["latin"]
})


export default function RootLayout({ children }) {


  return (
      <ClerkProvider>
        <html lang="en">
          <body
            className={outfit.className}
          >
          <Provider>
              {children}
          </Provider>
            <Toaster/>
          </body>
        </html>
      </ClerkProvider>
  );
}
